const CAT={interieur:['Intérieur','Peintures et primaires pour les murs intérieurs'],facade:['Façade','Peintures et enduits pour l\'extérieur'],etancheite:['Étanchéité','Protection des toitures et terrasses'],efect:['Décoratif efect','Effets marbre, métal et pierre']};
const P={
suten:{name:'Suten',ar:'سوتن',cat:'interieur',type:'Peinture intérieure satinée',fmt:'18 kg',img:'img/suten.webp',camp:'img/camp-suten.jpg',c:'#c9a24a',
 short:'Une finition satinée élégante et moderne pour les murs intérieurs.',
 desc:'Suten est la peinture intérieure satinée de Platinum. Elle donne aux murs une finition élégante et moderne, avec un léger éclat satiné.',
 pts:['Finition satinée','Murs intérieurs','Seau de 18 kg']},
sutenplus:{name:'Suten Plus',ar:'سوتن بلوس',cat:'interieur',type:'Peinture intérieure satinée',fmt:'18 kg',img:'img/sutenplus.webp',camp:'img/camp-sutenplus.jpg',c:'#1f3b2e',
 short:'La satinée intérieure, disponible dans les teintes du nuancier Platinum.',
 desc:'Suten Plus est une peinture intérieure satinée proposée dans les teintes du nuancier de couleurs Platinum, des tons doux aux couleurs audacieuses.',
 pts:['Finition satinée','Teintes du nuancier','Seau de 18 kg']},
unifix:{name:'Unifix',ar:'أونيفيكس',cat:'interieur',type:'Primaire et fixateur de fond',fmt:'20 kg',img:'img/unifix.webp',camp:'img/camp-unifix.jpg',c:'#7b3f74',
 short:'Primaire et fixateur de fond intérieur, spécial chantier.',
 desc:'Unifix prépare les surfaces avant la peinture : il assure l\'ancrage, unifie les fonds et fait gagner du temps sur chantier.',
 pts:['Adhérence maximale','Supprime les irrégularités','Spécial intérieur chantier','Application rapide']},
joker:{name:'Joker Plus',ar:'جوكر بلوس',cat:'facade',type:'Peinture façade professionnelle',fmt:'20 kg',img:'img/joker.webp',camp:'img/camp-joker.jpg',c:'#1d4a9e',
 short:'Protection durable et finition élégante pour les façades.',
 desc:'Joker Plus est une peinture façade respirante : elle laisse passer la vapeur d\'eau de l\'intérieur vers l\'extérieur, ne s\'écaille pas et ne se fissure pas.',
 pts:['Peinture respirante','Haute durabilité','Couleurs selon catalogue','Facile à appliquer'],
 tech:[['Rendement','6 à 10 m²/kg (plâtre, béton…)'],['Dilution','10 à 15 % d\'eau'],['Application','2 couches, 2 h entre les couches'],['Séchage','Toucher 15–20 min · poussière 1 h · complet 24 h']]},
easycoat:{name:'EasyCoat Plus EXT',ar:'إيزيكوت بلوس خارجي',cat:'facade',type:'Enduit de finition extérieur',fmt:'20 kg',img:'img/easycoat.webp',camp:'img/camp-easycoat.jpg',c:'#7a3f6e',
 short:'L\'enduit de finition pour des façades impeccables.',
 desc:'EasyCoat Plus EXT est un enduit de finition extérieur qui prépare les façades à une finition parfaite.',
 pts:['Résistance aux intempéries','Facilité d\'application','Finition parfaite']},
kola:{name:'Kola Plus',ar:'كولا بلوس',cat:'facade',type:'Résine pour finitions texturées',fmt:'29,5 kg',img:'img/kola.webp',camp:'img/camp-kola.jpg',c:'#1c3fa6',
 short:'Performance et esthétique pour les finitions texturées.',
 desc:'Kola Plus, présenté en fût de 29,5 kg, allie performance et esthétique pour des finitions texturées intérieures et extérieures.',
 pts:['Fût de 29,5 kg','Finitions texturées','Usage professionnel']},
trowel:{name:'Trowel Plaster',ar:'ترول بلاستر',cat:'facade',type:'Peinture décorative haut de gamme',fmt:'20 kg',img:'img/trowel.webp',camp:'img/camp-trowel.jpg',c:'#5d7d8f',
 short:'Enrichie de granulés naturels de marbre.',
 desc:'Trowel Plaster est une peinture décorative haut de gamme enrichie de granulés naturels de marbre, pour un rendu minéral.',
 pts:['Granulés naturels de marbre','Rendu minéral','Seau de 20 kg']},
waterblock:{name:'Waterblock',ar:'وتربلوك',cat:'etancheite',type:'Étanchéité liquide',fmt:'20 kg',img:'img/waterblock.webp',camp:'img/camp-waterblock.jpg',c:'#1b4c96',
 short:'100 % imperméable, sur tous les supports.',
 desc:'Waterblock protège toitures et terrasses contre l\'eau. Il s\'applique sur tous les supports : béton, tuile, zinc et PVC.',
 pts:['100 % imperméable','Béton, tuile, zinc, PVC','Toitures et terrasses']},
demarble:{name:'De Marble',ar:'دو ماربل',cat:'efect',type:'Peinture décorative effet marbre',fmt:'20 kg',img:'img/demarble.webp',camp:'img/camp-demarble.jpg',c:'#e88a1e',tex:'img/tex-marbre.jpg',
 short:'L\'élégance du marbre, directement sur vos murs.',
 desc:'De Marble, de la gamme décorative efect, reproduit l\'élégance du marbre sur les murs intérieurs.',
 pts:['Effet marbre','Gamme efect','Seau de 20 kg']},
fettalliage:{name:'Fettalliage',ar:'فيتالياج',cat:'efect',type:'Peinture décorative effet métallique',fmt:'1 kg',img:'img/fettalliage.webp',camp:'img/camp-fettalliage.jpg',c:'#4b2a4e',tex:'img/tex-metal.jpg',
 short:'Une touche d\'élégance métallique pour les murs intérieurs.',
 desc:'Fettalliage est une peinture décorative intérieure à effet métallique (alliage), de la gamme efect.',
 pts:['Effet métallique','Intérieur','Pot de 1 kg']},
texurentino:{name:'Texurentino',ar:'تيكسورنتينو',cat:'efect',type:'Enduit décoratif effet travertin',fmt:'20 kg',img:'img/texurentino.webp',camp:'img/camp-texurentino.jpg',c:'#c99a5b',tex:'img/tex-travertin.jpg',
 short:'Le charme du travertin antique, directement sur vos murs.',
 desc:'Texurentino est un enduit décoratif effet pierre travertin antique, appliqué à la taloche pour un rendu naturel.',
 pts:['Effet pierre travertin','Application à la taloche','Seau de 20 kg']}
};
const ORDER=['suten','sutenplus','unifix','joker','easycoat','kola','trowel','waterblock','demarble','fettalliage','texurentino'];
const NUANCIER=[['Ivoire','#efe6d2'],['Sable','#d9c09a'],['Ocre','#c98f3a'],['Terracotta','#c4623f'],['Corail','#e9765a'],['Bordeaux','#7c2235'],['Prune','#6b3b6e'],['Lavande','#a48cc8'],['Bleu nuit','#1f3a6e'],['Azur','#3d7cc9'],['Céladon','#9fbfa7'],['Vert forêt','#2f5a44'],['Gris perle','#c9cbcd'],['Anthracite','#3a3d42']];
const FB='https://www.facebook.com/search/top?q=Platinum%20Alg%C3%A9rie';
